Mr John would like you to create a Logistic Regression Model an Associated ROC curve for his cancer.csv dataset
in order to predict if the patient has cancer or not.
Dependent variable is Class:Benign=No cancer (2)
                            Malignant=cancer (4)


In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

In [2]:

data=pd.read_csv("cancer.csv")
data

id  Clump Thickness  UofCSize  UofCShape  Marginal Adhesion  \
0    1000025                5         1          1                  1   
1    1002945                5         4          4                  5   
2    1015425                3         1          1                  1   
3    1016277                6         8          8                  1   
4    1017023                4         1          1                  3   
..       ...              ...       ...        ...                ...   
678   776715                3         1          1                  1   
679   841769                2         1          1                  1   
680   888820                5        10         10                  3   
681   897471                4         8          6                  4   
682   897471                4         8          8                  5   

     SECSize  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0          2            1                3                1        1      2  
1          7           10                3                2        1      2  
2          2            2                3                1        1      2  
3          3            4                3                7        1      2  
4          2            1                3                1        1      2  
..       ...          ...              ...              ...      ...    ...  
678        3            2                1                1        1      2  
679        2            1                1                1        1      2  
680        7            3                8               10        2      4  
681        3            4               10                6        1      4  
682        4            5               10                4        1      4  

[683 rows x 11 columns]

In [3]:
data.drop(["id"],axis="columns",inplace=True)
data

Clump Thickness  UofCSize  UofCShape  Marginal Adhesion  SECSize  \
0                  5         1          1                  1        2   
1                  5         4          4                  5        7   
2                  3         1          1                  1        2   
3                  6         8          8                  1        3   
4                  4         1          1                  3        2   
..               ...       ...        ...                ...      ...   
678                3         1          1                  1        3   
679                2         1          1                  1        2   
680                5        10         10                  3        7   
681                4         8          6                  4        3   
682                4         8          8                  5        4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0              1                3                1        1      2  
1             10                3                2        1      2  
2              2                3                1        1      2  
3              4                3                7        1      2  
4              1                3                1        1      2  
..           ...              ...              ...      ...    ...  
678            2                1                1        1      2  
679            1                1                1        1      2  
680            3                8               10        2      4  
681            4               10                6        1      4  
682            5               10                4        1      4  

[683 rows x 10 columns]

In [4]:
data.isna().any()

Clump Thickness      False
UofCSize             False
UofCShape            False
Marginal Adhesion    False
SECSize              False
Bare Nuclei          False
Bland Chromatin      False
Normal Nucleoli      False
Mitoses              False
Class                False
dtype: bool

In [5]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
678    False
679     True
680    False
681    False
682    False
Length: 683, dtype: bool

In [11]:
data.drop_duplicates(inplace=True)

In [12]:
data

Clump Thickness  UofCSize  UofCShape  Marginal Adhesion  SECSize  \
0                  5         1          1                  1        2   
1                  5         4          4                  5        7   
2                  3         1          1                  1        2   
3                  6         8          8                  1        3   
4                  4         1          1                  3        2   
..               ...       ...        ...                ...      ...   
677                3         1          1                  1        2   
678                3         1          1                  1        3   
680                5        10         10                  3        7   
681                4         8          6                  4        3   
682                4         8          8                  5        4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0              1                3                1        1      2  
1             10                3                2        1      2  
2              2                3                1        1      2  
3              4                3                7        1      2  
4              1                3                1        1      2  
..           ...              ...              ...      ...    ...  
677            1                2                1        2      2  
678            2                1                1        1      2  
680            3                8               10        2      4  
681            4               10                6        1      4  
682            5               10                4        1      4  

[449 rows x 10 columns]

In [13]:
data.dtypes

Clump Thickness      int64
UofCSize             int64
UofCShape            int64
Marginal Adhesion    int64
SECSize              int64
Bare Nuclei          int64
Bland Chromatin      int64
Normal Nucleoli      int64
Mitoses              int64
Class                int64
dtype: object

In [14]:
data.shape

(449, 10)

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 449 entries, 0 to 682
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Clump Thickness    449 non-null    int64
 1   UofCSize           449 non-null    int64
 2   UofCShape          449 non-null    int64
 3   Marginal Adhesion  449 non-null    int64
 4   SECSize            449 non-null    int64
 5   Bare Nuclei        449 non-null    int64
 6   Bland Chromatin    449 non-null    int64
 7   Normal Nucleoli    449 non-null    int64
 8   Mitoses            449 non-null    int64
 9   Class              449 non-null    int64
dtypes: int64(10)
memory usage: 38.6 KB


In [19]:
data["Class"] = data["Class"].astype("category")
data.dtypes

Clump Thickness         int64
UofCSize                int64
UofCShape               int64
Marginal Adhesion       int64
SECSize                 int64
Bare Nuclei             int64
Bland Chromatin         int64
Normal Nucleoli         int64
Mitoses                 int64
Class                category
dtype: object

In [20]:
data["Class"] = data["Class"].cat.codes

In [21]:
data

Clump Thickness  UofCSize  UofCShape  Marginal Adhesion  SECSize  \
0                  5         1          1                  1        2   
1                  5         4          4                  5        7   
2                  3         1          1                  1        2   
3                  6         8          8                  1        3   
4                  4         1          1                  3        2   
..               ...       ...        ...                ...      ...   
677                3         1          1                  1        2   
678                3         1          1                  1        3   
680                5        10         10                  3        7   
681                4         8          6                  4        3   
682                4         8          8                  5        4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0              1                3                1        1      0  
1             10                3                2        1      0  
2              2                3                1        1      0  
3              4                3                7        1      0  
4              1                3                1        1      0  
..           ...              ...              ...      ...    ...  
677            1                2                1        2      0  
678            2                1                1        1      0  
680            3                8               10        2      1  
681            4               10                6        1      1  
682            5               10                4        1      1  

[449 rows x 10 columns]

In [22]:
y=data["Class"]
print(y)

0      0
1      0
2      0
3      0
4      0
      ..
677    0
678    0
680    1
681    1
682    1
Name: Class, Length: 449, dtype: int8


In [23]:
X=data[["Clump Thickness","UofCSize","UofCShape","Marginal Adhesion","SECSize","Bare Nuclei","Bland Chromatin","Normal Nucleoli","Mitoses"]]
print(X)

     Clump Thickness  UofCSize  UofCShape  Marginal Adhesion  SECSize  \
0                  5         1          1                  1        2   
1                  5         4          4                  5        7   
2                  3         1          1                  1        2   
3                  6         8          8                  1        3   
4                  4         1          1                  3        2   
..               ...       ...        ...                ...      ...   
677                3         1          1                  1        2   
678                3         1          1                  1        3   
680                5        10         10                  3        7   
681                4         8          6                  4        3   
682                4         8          8                  5        4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  
0              1                3                1        1  

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [28]:
model= LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [33]:
y_pred=model.predict(X_test)
y_pred

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0], dtype=int8)

In [35]:
model.predict([[4,8,8,5,4,5,10,4,1]])

C:\Users\HAWA ABDALLAH\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int8)

model.predict([[4,8,8,5,4,5,10,4,1]])

In [30]:
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(model.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.93


In [31]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[55  5]
 [ 4 71]]


In [32]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.92      0.92        60
           1       0.93      0.95      0.94        75

    accuracy                           0.93       135
   macro avg       0.93      0.93      0.93       135
weighted avg       0.93      0.93      0.93       135

